/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ShareUrlUrlImport } from './routes/share-url.$url'
import { Route as DownloadUrlImport } from './routes/download.$url'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ShareUrlUrlRoute = ShareUrlUrlImport.update({
  id: '/share-url/$url',
  path: '/share-url/$url',
  getParentRoute: () => rootRoute,
} as any)

const DownloadUrlRoute = DownloadUrlImport.update({
  id: '/download/$url',
  path: '/download/$url',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/download/$url': {
      id: '/download/$url'
      path: '/download/$url'
      fullPath: '/download/$url'
      preLoaderRoute: typeof DownloadUrlImport
      parentRoute: typeof rootRoute
    }
    '/share-url/$url': {
      id: '/share-url/$url'
      path: '/share-url/$url'
      fullPath: '/share-url/$url'
      preLoaderRoute: typeof ShareUrlUrlImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/download/$url': typeof DownloadUrlRoute
  '/share-url/$url': typeof ShareUrlUrlRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/download/$url': typeof DownloadUrlRoute
  '/share-url/$url': typeof ShareUrlUrlRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/download/$url': typeof DownloadUrlRoute
  '/share-url/$url': typeof ShareUrlUrlRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/download/$url' | '/share-url/$url'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/download/$url' | '/share-url/$url'
  id: '__root__' | '/' | '/download/$url' | '/share-url/$url'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadUrlRoute: typeof DownloadUrlRoute
  ShareUrlUrlRoute: typeof ShareUrlUrlRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadUrlRoute: DownloadUrlRoute,
  ShareUrlUrlRoute: ShareUrlUrlRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/download/$url",
        "/share-url/$url"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/download/$url": {
      "filePath": "download.$url.tsx"
    },
    "/share-url/$url": {
      "filePath": "share-url.$url.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
