/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ShareUrlImport } from './routes/share-url'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ShareUrlRoute = ShareUrlImport.update({
  id: '/share-url',
  path: '/share-url',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/share-url': {
      id: '/share-url'
      path: '/share-url'
      fullPath: '/share-url'
      preLoaderRoute: typeof ShareUrlImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/share-url': typeof ShareUrlRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/share-url': typeof ShareUrlRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/share-url': typeof ShareUrlRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/share-url'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/share-url'
  id: '__root__' | '/' | '/share-url'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShareUrlRoute: typeof ShareUrlRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShareUrlRoute: ShareUrlRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/share-url"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/share-url": {
      "filePath": "share-url.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
